services:
  - type: web
    name: loan-prolog-app
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y swi-prolog
      pip install -r requirements.txt
    startCommand: gunicorn app:app
